"""Add genres column to Anime table.

Revision ID: 9eabdd982c95
Revises: 3a1d0c331836
Create Date: 2025-09-04 22:52:43.940085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eabdd982c95'
down_revision = '3a1d0c331836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
